import {
  SLOT_ORDER,
  SLOT_NAMES,
  RANKS,
  RARITIES,
  LOOT_SOURCES,
  ITEM_BASES,
  ITEM_ARCHETYPES,
  STAT_BUDGETS,
  AFFIXES,
  ZONES,
  JOBS,
  PETS,
  SKILLS,
  ACHIEVEMENTS,
} from '../../shared/content/game-data.js';

import {
  TABS,
  VIEWS,
  VIEW_META,
  VIEW_GROUPS,
  MOBILE_PRIMARY_VIEWS,
  MOBILE_OVERFLOW_VIEWS,
} from '../../shared/content/ui-meta.js';

const STORAGE_KEY = 'aether_arena_pbbg_v3';

window.AetherConfig = {
  STORAGE_KEY,
  SLOT_ORDER,
  SLOT_NAMES,
  TABS,
  VIEWS,
  VIEW_META,
  VIEW_GROUPS,
  MOBILE_PRIMARY_VIEWS,
  MOBILE_OVERFLOW_VIEWS,
  RANKS,
  RARITIES,
  LOOT_SOURCES,
  ITEM_BASES,
  ITEM_ARCHETYPES,
  STAT_BUDGETS,
  AFFIXES,
  ZONES,
  JOBS,
  PETS,
  SKILLS,
  ACHIEVEMENTS,
};
